Release v2.0.0
Blagues-API/blagues-api-php pull request #17
Opened 2023-07-13 00:05 UTC by Zuruuh

2023-07-13 07:30 UTC, DraftProducts requested changes
Super taff, j'ai pas vraiment la possibilité de review comme il se doit le code php donc je me suis concentré sur les conventions & doc.

2023-07-13 07:30 UTC, DraftProducts commented on readme.md
`readme.md` => `README.md`

2023-07-13 07:30 UTC, DraftProducts commented on contributing.md
`contributing.md` => `CONTRIBUTING.md`

2023-07-13 07:30 UTC, DraftProducts commented on contributing.md
>  ## 2 - Linters
```suggestion
## Linters
```

2023-07-13 07:30 UTC, DraftProducts commented on composer.json
> +            "Zuruuh\\BlaguesApi\\": "src/"
```suggestion
            "BlaguesApi\\": "src/"
```

2023-07-13 10:10 UTC, DraftProducts requested changes

2023-07-13 10:10 UTC, DraftProducts commented on CODEOWNERS
> +* @Blagues-API
```suggestion
* @Zuruuh
```

2023-07-13 13:41 UTC, merged

2023-07-14 10:31 UTC, DraftProducts commented
C’est publié ? @Zuruuh

2023-07-14 11:18 UTC, Zuruuh commented
> C’est publié ? @Zuruuh 

yes 👍